### ISSUE TITLE
上传文件缓存区溢出

### ISSUE THREAD

**Issue by xianjimli** [ideawu/tftpx#4]
client.c:195行：

```
sprintf(snd_packet.filename, "%s%c%s%c%d%c", filename, 0, "octet", 0, blocksize, 0);
```

很好奇文件名为什么只有2个字节长度？

```
struct tftpx_packet{
    ushort cmd;
    union{
        ushort code;
        ushort block;
        // For a RRQ and WRQ TFTP packet
        char filename[2];
    };
    char data[DATA_SIZE];
};
```

**Comment by xianjimli** [comment]
我知道怎么回事了，filename只是用来定位内存地址，改成这样就行了：
    char* data = snd_packet.filename;
    sprintf(data, "%s%c%s%c%d%c", remote_file, 0, "octet", 0, blocksize, 0);
否则在MacOS上会死到这里：
#0  0x00007fff94da2f06 in __pthread_kill () from /usr/lib/system/libsystem_kernel.dylib
#1  0x00007fff926b74ec in pthread_kill () from /usr/lib/system/libsystem_pthread.dylib
#2  0x00007fff8a7596df in abort () from /usr/lib/system/libsystem_c.dylib
#3  0x00007fff8a759856 in abort_report_np () from /usr/lib/system/libsystem_c.dylib
#4  0x00007fff8a77fa0c in __chk_fail () from /usr/lib/system/libsystem_c.dylib
#5  0x00007fff8a77f9dc in __chk_fail_overflow () from /usr/lib/system/libsystem_c.dylib
#6  0x00007fff8a77fef8 in __sprintf_chk () from /usr/lib/system/libsystem_c.dylib
#7  0x00000001000012ef in do_get ()
